import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'
import Footer from './components/Footer'
import NavBarTwo from './components/NavBarTwo'
import NavBarThree from './components/NavBarThree'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Agency Template',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NavBar title={metadata.title}/> */}
        {/* <NavBarTwo/> */}
        <NavBarThree/>
        {children}
        <Footer title={metadata.title}/>
      </body>
    </html>
  )
}
